#!/usr/bin/env python

#
# Script for generating new folder and html/json data for a new project
#
# @author Natesh Narain <nnaraindev@gmail.com>
# @date September 16 2016

import os

from argparse import ArgumentParser

# TODO: Project JSON data addition

parser = ArgumentParser()
parser.add_argument('-t', '--title', required=True, help='projec title')

args = vars(parser.parse_args())

title = args['title']

def main():
    # new project folder path
    path = os.path.join('projects', title)
    if not os.path.exists(path):
        os.mkdir(path)

    with open(os.path.join(path, 'index.html'), 'w+') as file:
        file.write('---\n')
        file.write('layout: default\n') # TODO change when adding new project page layout
        file.write('title: %s\n' % (title))
        file.write('---\n')

        file.write('\n\n')

if __name__ == '__main__':
    main()
