#!/usr/bin/env python

#
# Script for generating new posts for my jekyll base blog
#
# @author Natesh Narain

import os
import datetime

import requests
import json

from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument('-t', '--title', required=True,              help='post title')
parser.add_argument('-d', '--description',                       help='post description')
parser.add_argument('-l', '--tags',                              help='post tags')
parser.add_argument('-i', '--thumbnail',                         help='post thumbnail')

args = vars(parser.parse_args())

post_title = args['title']
post_des   = args['description'] if args['description'] else ''
post_tags  = args['tags'] if args['tags'] else ''
post_thumb = args['thumbnail'] if args['thumbnail'] else ''

def main():

	# create the date string
	date = datetime.datetime.now()
	date_string = "%d-%02d-%02d-" % (date.year, date.month, date.day)
	date_path = date_string.replace('-', '/')

	# create the file name
	file_name = date_string + post_title + ".md"

	# create the post file and add the yaml front matter
	with open("_posts/" + file_name, 'w+') as file:
		file.write("---\n")
		file.write("layout: post\n")
		file.write("title: "  + post_title + "\n")
		file.write("description: %s\n" % (post_des))
		file.write("tag: %s\n" % (post_tags))
		file.write("thumbnail: /assets/%s%s\n" % (date_path, post_thumb))
		file.write("repo_url: \n")
		file.write("---\n\n")

	# create the date's asset folder
	date_array = [str(date.year), "%02d" % (date.month), "%02d" % (date.day)]

	path = 'assets/'

	for e in date_array:
		path = path + e + "/"
		if not os.path.exists(path):
			os.mkdir(path)

# run
if __name__ == '__main__':
	main()
